# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/czLandscapingTk/',
                'doc_host': 'https://GullyBurns.github.io',
                'git_url': 'https://github.com/GullyBurns/czLandscapingTk/tree/master/',
                'lib_path': 'czLandscapingTk'},
  'syms': {}}
