# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NCBI_Database_Type": "00_search_engine_eutils.ipynb",
         "ESearchQuery": "00_search_engine_eutils.ipynb",
         "PAGE_SIZE": "00_search_engine_eutils.ipynb",
         "TIME_THRESHOLD": "00_search_engine_eutils.ipynb",
         "EFetchQuery": "00_search_engine_eutils.ipynb",
         "EuroPMCQuery": "00_search_engine_eutils.ipynb",
         "QueryType": "01_query_translator.ipynb",
         "QueryTranslator": "01_query_translator.ipynb",
         "NetworkxS2AG": "02_networkxS2AG.ipynb"}

modules = ["searchEngineUtils.py",
           "queryTranslator.py",
           "networkXS2AG.py"]

doc_url = "https://GullyBurns.github.io/czLandscapingTk/"

git_url = "https://github.com/GullyBurns/czLandscapingTk/tree/master/"

def custom_doc_links(name): return None
