# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NetworkxS2AG": "02_networkxS2AG.ipynb"}

modules = ["kolsOnS2AG.py"]

doc_url = "https://GullyBurns.github.io/czLandscapingTk/"

git_url = "https://github.com/GullyBurns/czLandscapingTk/tree/master/"

def custom_doc_links(name): return None
