# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbdev/utils/08_bioLinkUtils.ipynb.

# %% auto 0
__all__ = ['rare_sparql', 'parent_sparql', 'child_sparql', 'siblings_sparql', 'descendents_sparql', 'rare_diseases_sparql']

# %% ../nbdev/utils/08_bioLinkUtils.ipynb 4
rare_sparql = '''
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?d 
WHERE {
  ?d rdf:type owl:Class .
  ?d rdfs:label ?dName .
  ?d rdfs:subClassOf+ obo:MONDO_0000001 .
  ?d rdfs:subClassOf+ ?t .
  ?t rdf:type owl:Restriction .
  ?t owl:onProperty obo:RO_0002573 .
  ?t owl:someValuesFrom obo:MONDO_0021136 .
}'''

parent_sparql = '''PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?parent_id ?parent_name
WHERE {
	?mondo_id rdf:type owl:Class .
    ?mondo_id rdfs:label ?name .
    ?mondo_id rdfs:subClassOf ?parent_id .
    ?parent_id rdfs:label ?parent_name .
}'''

parent_sparql = '''PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?parent_id ?parent_name
WHERE {
	?mondo_id rdf:type owl:Class .
    ?mondo_id rdfs:label ?name .
    ?mondo_id rdfs:subClassOf ?parent_id .
    ?parent_id rdfs:label ?parent_name .
}'''

child_sparql = '''PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?child_id ?child_name
WHERE {
	?mondo_id rdf:type owl:Class .
    ?mondo_id rdfs:label ?name .
    ?child_id rdfs:subClassOf ?mondo_id .
    ?child_id rdfs:label ?child_name .
}'''

siblings_sparql = '''PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT DISTINCT ?d2 ?d2Name
WHERE {
  ?mondo_id rdf:type owl:Class .
  ?mondo_id rdfs:label ?mondo_Name .
  ?mondo_id rdfs:subClassOf ?p .
  ?d2 rdf:type owl:Class .
  ?d2 rdfs:label ?d2Name .
  ?d2 rdfs:subClassOf ?p .
}'''

descendents_sparql = '''
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?name ?parent_id ?parent_name ?descendent_id ?descendent_name
WHERE {
    ?mondo_id rdfs:label ?name .
    ?descendent_id rdfs:subClassOf+ ?mondo_id .
    ?descendent_id rdfs:label ?descendent_name .
    ?descendent_id rdfs:subClassOf ?parent_id .
	?parent_id rdfs:label ?parent_name .
} '''

rare_diseases_sparql = '''
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?name ?parent_id ?parent_name ?descendent_id ?descendent_name
WHERE {
    ?mondo_id rdfs:label ?name .
    ?descendent_id rdfs:subClassOf+ ?mondo_id .
    ?descendent_id rdfs:label ?descendent_name .
    ?descendent_id rdfs:subClassOf ?parent_id .
	?parent_id rdfs:label ?parent_name .
} '''
